(add-to-list 'load-path "~/.dotfiles/emacs/.config/emacs/ftplugin/")
(add-to-list 'load-path "~/.dotfiles/emacs/.config/emacs/lisp/ximon/")
(add-to-list 'load-path "~/.dotfiles/emacs/.config/emacs/lisp/ximon/core/")
(add-to-list 'load-path "~/.dotfiles/emacs/.config/emacs/lisp/ximon/packages/")
(add-to-list 'load-path "~/.dotfiles/emacs/.config/emacs/lisp/ximon/packages/lsp/")

(require 'org-config)
(require 'straight)

(require 'settings) 
(require 'options)
(require 'keymaps)
(require 'colorscheme)

(require 'helpful)
(require 'doom-dashboard)
(require 'doom-modeline)
(require 'evil)
(require 'neotree)
(require 'wakatime)
(require 'lsp-mode-config)
(require 'grammarly)
(require 'org-superstar)
